const MockData = [
  {
    id: 1,
    name: "Ephemeral Echoes",
    author: "Aria Sinclair",
    currentChapter: 15,
    chapterName: "Whispers in the Wind",
    bookmarkDate: "2023-11-30",
    bookmarkTime: "10:15:00",
    pictureSource: "https://source.unsplash.com/400x600/?book",
  },
  {
    id: 2,
    name: "Midnight Serenade",
    author: "Sebastian Nightingale",
    currentChapter: 8,
    chapterName: "Moonlit Melodies",
    bookmarkDate: "2023-11-29",
    bookmarkTime: "18:30:00",
    pictureSource: "https://source.unsplash.com/400x600/?novel",
  },
  {
    id: 3,
    name: "Whispers of Destiny",
    author: "Luna Starlight",
    currentChapter: 22,
    chapterName: "Fate's Embrace",
    bookmarkDate: "2023-11-28",
    bookmarkTime: "14:45:00",
    pictureSource: "https://source.unsplash.com/400x600/?fantasy",
  },
  {
    id: 4,
    name: "Whirlwind Chronicles",
    author: "Elijah Stormbringer",
    currentChapter: 12,
    chapterName: "Storm's Wrath",
    bookmarkDate: "2023-11-27",
    bookmarkTime: "21:00:00",
    pictureSource: "https://source.unsplash.com/400x600/?storm",
  },
  {
    id: 5,
    name: "Celestial Symphony",
    author: "Aurora Harmony",
    currentChapter: 30,
    chapterName: "Harmony's Ascendance",
    bookmarkDate: "2023-11-26",
    bookmarkTime: "11:45:00",
    pictureSource: "https://source.unsplash.com/400x600/?celestial",
  },
  {
    id: 6,
    name: "Shadowed Secrets",
    author: "Dante Nightshade",
    currentChapter: 18,
    chapterName: "Veil of Shadows",
    bookmarkDate: "2023-11-25",
    bookmarkTime: "17:30:00",
    pictureSource: "https://source.unsplash.com/400x600/?mystery",
  },
];

export default MockData;
